Name:           ros-indigo-utilrb
Version:        2.8.0
Release:        0%{?dist}
Summary:        ROS utilrb package

Group:          Development/Libraries
License:        CeCILL-B (BSD-like)
Source0:        %{name}-%{version}.tar.gz

Requires:       openssl-devel
Requires:       readline
Requires:       ros-indigo-catkin
Requires:       ruby
Requires:       ruby-devel
Requires:       rubygem-facets
Requires:       rubygem-hoe
Requires:       rubygems
BuildRequires:  cmake
BuildRequires:  openssl-devel
BuildRequires:  readline-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ruby
BuildRequires:  ruby-devel
BuildRequires:  rubygem-facets
BuildRequires:  rubygem-hoe
BuildRequires:  rubygem-rake-compiler
BuildRequires:  rubygems

%description
Ruby toolkit: This library is a collection of useful Ruby classes

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Jan 25 2015 Orocos Development Team <orocos-dev@lists.mech.kuleuven.be> - 2.8.0-0
- Autogenerated by Bloom

